version: '2'
services:
    weportfolio-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/WEPortfolio/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=WEPortfolio
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
